package user_interface.reports;

import controllers.ManejadorVentanaReportes;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JTable;
import models.token.TipoToken;
import models.token.Token;

/**
 *
 * @author Manu
 */
public class VentanaReportes extends javax.swing.JFrame {

    /**
     * Creates new form VentanaReporteTokens
     */
    private List<Token> tokens;
    private ManejadorVentanaReportes manejador;
    private TipoReporte tipoReporte;

    public VentanaReportes(List<Token> tokens, TipoReporte tipoReporte) {
        initComponents();
        setVisible(true);
        setResizable(false);
        setLocationRelativeTo(null);
        this.tokens = tokens;
        this.tipoReporte = tipoReporte;
        this.manejador = new ManejadorVentanaReportes(this);
        manejador.setTituloLabel();
        manejador.actualizarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReports = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte");

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTitulo.setText("Reporte de Tokens");
        getContentPane().add(labelTitulo, java.awt.BorderLayout.NORTH);

        tablaReports.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tablaReports);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTable tablaReports;
    // End of variables declaration//GEN-END:variables

    public List<Token> getTokens() {
        return tokens;
    }

    public JTable getTablaReports() {
        return tablaReports;
    }

    public TipoReporte getTipoReporte() {
        return tipoReporte;
    }

    public JLabel getLabelTitulo() {
        return labelTitulo;
    }

}
