package user_interface;

import controllers.ManejadorVentanaBuscar;
import javax.swing.*;
import javax.swing.text.JTextComponent;

/**
 * 
 * Clase que se encarga de mostrarle al usuario la interfaz para buscar palabras
 * dentro de la aplicación
 *
 * @author Manu
 */
public class VentanaBuscar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBuscar
     */
    private JTextComponent areaTexto;
    private ManejadorVentanaBuscar manejador;

    /**
     * Contructor para crear un nuevo frame para buscar
     * 
     * @param areaTexto El componente de texto sobre el cual se buscará la palabra.
     */

    public VentanaBuscar(JTextComponent areaTexto) {
        this.areaTexto = areaTexto;
        initComponents();
        setVisible(true);
        setResizable(false);
        this.manejador = new ManejadorVentanaBuscar(this);
        manejador.activarBotones();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textBuscar = new javax.swing.JTextField();
        botonSiguiente = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        labelBusqueda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textBuscarKeyReleased(evt);
            }
        });

        botonSiguiente.setText("Buscar siguiente");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addContainerGap(38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 333,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup().addComponent(labelBusqueda)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonSiguiente).addGap(18, 18, 18).addComponent(botonSalir)))
                        .addGap(25, 25, 25)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(53, 53, 53)
                        .addComponent(textBuscar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botonSiguiente).addComponent(botonSalir).addComponent(labelBusqueda))
                        .addContainerGap(35, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonSalirActionPerformed
        dispose();
    }// GEN-LAST:event_botonSalirActionPerformed

    private void textBuscarKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_textBuscarKeyReleased
        manejador.activarBotones();
    }// GEN-LAST:event_textBuscarKeyReleased

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonSiguienteActionPerformed
        // manejador.buscar();
        manejador.highLight(areaTexto, textBuscar.getText());
    }// GEN-LAST:event_botonSiguienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JLabel labelBusqueda;
    private javax.swing.JTextField textBuscar;
    // End of variables declaration//GEN-END:variables

    public JTextComponent getAreaTexto() {
        return areaTexto;
    }

    public JTextField getTextBuscar() {
        return textBuscar;
    }

    public JLabel getLabelBusqueda() {
        return labelBusqueda;
    }

    public JButton getBotonSiguiente() {
        return botonSiguiente;
    }

}
