package user_interface;

import archives.ManejoArchivo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import models.token.Token;
import principal.ValidadorTokens;
import util.TextLineNumber;

/**
 *
 * @author Manu
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    private ValidadorTokens afd;
    private List<Token> tokens;
    private TextLineNumber numeroLinea;
    public VentanaPrincipal() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        numeroLinea = new TextLineNumber(jTextPane1);
        jScrollPane1.setRowHeaderView(numeroLinea);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        textFieldBuscar = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemAbrirArchivo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemValidarTexto = new javax.swing.JMenuItem();
        jMenuItemLimpiarPantalla = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemReportErrores = new javax.swing.JMenuItem();
        jMenuItemReportTokens = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));

        jTextPane1.setBackground(new java.awt.Color(40, 40, 40));
        jTextPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextPane1.setPreferredSize(new java.awt.Dimension(62, 500));
        jScrollPane1.setViewportView(jTextPane1);

        jPanel3.add(jScrollPane1);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        textFieldBuscar.setText("Buscar palabra...");
        textFieldBuscar.setPreferredSize(new java.awt.Dimension(800, 30));
        textFieldBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textFieldBuscarMousePressed(evt);
            }
        });
        textFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(textFieldBuscar, java.awt.BorderLayout.CENTER);

        botonBuscar.setText("Buscar");
        botonBuscar.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel2.add(botonBuscar, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu4.setText("Archivo");

        jMenuItemAbrirArchivo.setText("Abrir Archivo...");
        jMenuItemAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirArchivoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemAbrirArchivo);

        jMenuItem1.setText("Guardar como...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);
        jMenu4.add(jSeparator1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar2.add(jMenu4);

        jMenu1.setText("Acciones");

        jMenuItemValidarTexto.setText("Validar Texto");
        jMenuItemValidarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemValidarTextoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemValidarTexto);

        jMenuItemLimpiarPantalla.setText("Limpiar pantalla");
        jMenuItemLimpiarPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLimpiarPantallaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLimpiarPantalla);

        jMenuBar2.add(jMenu1);

        jMenu5.setText("Reportes");

        jMenuItemReportErrores.setText("Reporte de errores");
        jMenu5.add(jMenuItemReportErrores);

        jMenuItemReportTokens.setText("Reporte de Tokens");
        jMenu5.add(jMenuItemReportTokens);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuscarActionPerformed
        textFieldBuscar.setText("");
    }//GEN-LAST:event_textFieldBuscarActionPerformed

    private void textFieldBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldBuscarMousePressed
        textFieldBuscar.setText("");
    }//GEN-LAST:event_textFieldBuscarMousePressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirArchivoActionPerformed
        List<String> lineas = ManejoArchivo.getLinesTextFile(ManejoArchivo.getFileChooserPath());
        jTextPane1.setText("");
        if (!lineas.isEmpty()) {
            String salto = "\n";
            for (int i = 0; i < lineas.size(); i++) {
                if (i+1 == lineas.size()) {
                    salto = "";
                }
                jTextPane1.setText(jTextPane1.getText() + lineas.get(i) + salto);
                
            }
        }else{
            JOptionPane.showMessageDialog(null, "El archivo de texto se encuentra vacío", "Archivo vacio", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jMenuItemAbrirArchivoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (jTextPane1.getText() != null && !jTextPane1.getText().isBlank()) {
            ManejoArchivo.guardarArchivoTxt(ManejoArchivo.getFileChooserPath(), jTextPane1.getText());
        }else{
            JOptionPane.showMessageDialog(null, "No hay contenido para guardar, escriba algo primero en el area de texto", "Area de texto vacía", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemLimpiarPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLimpiarPantallaActionPerformed
        jTextPane1.setText("");
    }//GEN-LAST:event_jMenuItemLimpiarPantallaActionPerformed

    private void jMenuItemValidarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemValidarTextoActionPerformed
        tokens = new ArrayList<>();
        afd = new ValidadorTokens(jTextPane1.getText(), tokens);
    }//GEN-LAST:event_jMenuItemValidarTextoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAbrirArchivo;
    private javax.swing.JMenuItem jMenuItemLimpiarPantalla;
    private javax.swing.JMenuItem jMenuItemReportErrores;
    private javax.swing.JMenuItem jMenuItemReportTokens;
    private javax.swing.JMenuItem jMenuItemValidarTexto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField textFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
